services:
  # Web Service
  - type: web
    name: spectra-app
    env: node
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_APP_URL
        value: https://spectra-app-fb05.onrender.com
      - key: SCOPES
        value: write_products,write_product_listings,read_product_listings,read_inventory
    disk:
      name: data
      mountPath: /opt/render/project/data
      sizeGB: 1
