# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2e4575da88ccd972711896dd2f76e5ec"
application_url = "https://spectra-app-fb05.onrender.com"
embedded = true
name = "spectra-variant-images"

[access_scopes]
scopes = "read_products"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://spectra-app-fb05.onrender.com/api/auth", "https://spectra-app-fb05.onrender.com/auth/tokens" ]

[build]
automatically_update_urls_on_dev = true
